# This is a basic workflow to help you get started with Actions

name: CI for pull requests

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: 
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
    
      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/setup@v0
      
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: '["${{github.workspace}}/Espd/package.json"]'
        env: 
          PACKAGE_VERSION: '${{steps.gitversion.outputs.semVer}}'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.200'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}} # Note, create a secret with this name in Settings
           
      - name: Dotnet build and test
        run: dotnet test --configuration Release $GITHUB_WORKSPACE
      
      - name: Publish code lists
        run: dotnet run --project $GITHUB_WORKSPACE/ResourceExporter/ResourceExporter.csproj 

    #  - uses: actions/setup-node@v1
    #    with:
    #      node-version: 10
    #  - name: Npm install
    #    run: | 
    #      cd $GITHUB_WORKSPACE/Espd/
    #      npm install
    #  - name: Typescript build
    #    run: | 
    #      cd $GITHUB_WORKSPACE/Espd/
    #      npm run tsbuild
      
