# This is a basic workflow to help you get started with Actions

name: CI for pull requests

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: 
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.1.200'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}} # Note, create a secret with this name in Settings
           
      - name: Dotnet build and test
        run: dotnet test --configuration Release $GITHUB_WORKSPACE
      
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Typescript build
        run: | 
          cd $GITHUB_WORKSPACE/Espd/
          npm install
          npm run tsbuild
      