# This is a basic workflow to help you get started with Actions

name: Hilma Espd EDM CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: 
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set env
      run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    
    - uses: gittools/actions/gitversion/setup@v0.9
      with:
        versionSpec: '5.1.x'  
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9
    
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: '["${{github.workspace}}/Espd/package.json","${{github.workspace}}/Espd/.npmrc"]'
      env: 
        AZURE_DEVOPS_PAT_BASE64ENCODED: '${{secrets.AZURE_DEVOPS_PAT_BASE64ENCODED}}'
        NPM_VERSION: '${{steps.gitversion.outputs.nuGetVersion}}'
    
    - uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.200'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}} # Note, create a secret with this name in Settings
         
    - name: Dotnet build and test
      run: dotnet test --configuration Release $GITHUB_WORKSPACE        
  
    - name: Create Nuget package
      run: dotnet pack --no-build --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }} $GITHUB_WORKSPACE     
  
    - name: Publish the package to Hilma Azure Artifacts feed
      run: dotnet nuget push $GITHUB_WORKSPACE/**/*.nupkg -k ${{secrets.NUGET_AUTH_TOKEN}}

    - name: Publish npm
      uses: pascalgn/npm-publish-action@51fdb4531e99aac1873764ef7271af448dc42ab4
      with: # All of theses inputs are optional
        tag_name: "v%s"
        tag_message: "v%s"
      env: # More info about the environment variables in the README
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings    
